### ISSUE TITLE
when using webpack 5 and importing @lightningrodlabs/we-applet, when I try to build I get this. 

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/we#9]
ERROR in ../node_modules/@lightningrodlabs/we-applet/dist/api.js 2:0-38
Module not found: Error: Can't resolve './utils' in '/Users/connor/code/acorn/node_modules/@lightningrodlabs/we-applet/dist'
Did you mean 'utils.js'?
BREAKING CHANGE: The request './utils' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
resolve './utils' in '/Users/connor/code/acorn/node_modules/@lightningrodlabs/we-applet/dist'
  using description file: /Users/connor/code/acorn/node_modules/@lightningrodlabs/we-applet/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/connor/code/acorn/node_modules/@lightningrodlabs/we-applet/package.json (relative path: ./dist/utils)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/connor/code/acorn/node_modules/@lightningrodlabs/we-applet/dist/utils doesn't exist
 @ ../node_modules/@lightningrodlabs/we-applet/dist/index.js 1:0-25 1:0-25
 @ ./src/index.tsx 20:0-68 22:5-16 29:31-47

webpack 5.89.0 compiled with 1 error in 22095 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Connoropolous** [comment]
after changing `api.js` import line

from `import { postMessage } from './utils';
to
import { postMessage } from './utils.js';

**Comment by matthme** [comment]
Thank you! Totally forgot about that but should be fixed now as of `@lightningrodlabs/we-applet@0.16.2`.
